apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meu-servico-ingress
spec:
  rules:
    - http:
        paths:
          - path: /meu-servico
            pathType: Prefix
            backend:
              service:
                name: meu-servico
                port:
                  number: 80
